apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ppro-task-helloworld.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ template "ppro-task-helloworld.name" . }}
    chart: {{ template "ppro-task-helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ppro-task-helloworld.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ppro-task-helloworld.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP    
          resources:
{{ toYaml .Values.resources | indent 12 }}
